# Generated by Django 4.0.6 on 2022-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('Competitive', 'Competitive'), ('Event', 'Event'), ('Program', 'Program'), ('Course', 'Course')], default='Program', max_length=20),
        ),
    ]
