# Generated by Django 4.0.6 on 2022-07-13 16:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Allops', '0002_opportunity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='details',
            field=models.TextField(default='head over to official link for more details!'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(default='virtual', max_length=64),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Scholarship', 'Scholarship'), ('Apprenticeships', 'Apprenticeships'), ('Training', 'Training'), ('Product Management', 'Product Management'), ('Language', 'Language'), ('Social Good', 'Social Good'), ('Machine Learning/AI', 'Machine Learning/AI'), ('Blockchain', 'Blockchain'), ('Design', 'Design'), ('Web', 'Web'), ('Health', 'Health'), ('AR/VR', 'AR/VR'), ('Gaming', 'Gaming'), ('Fintech', 'Fintech'), ('IoT', 'IoT'), ('DevOps', 'DevOps'), ('Cloud', 'Cloud'), ('Lifehacks', 'Lifehacks'), ('Cybersecurity', 'Cybersecurity'), ('Voice skills', 'Voice skills'), ('Mobile', 'Mobile'), ('Music/Art', 'Music/Art')], max_length=228),
        ),
    ]
