# Generated by Django 4.0.6 on 2022-08-12 18:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Allops', '0005_remove_user_fields_remove_user_mails_mails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Externship', 'Externship'), ('Student Program', 'Student Program'), ('Scholarship', 'Scholarship'), ('Apprenticeship', 'Apprenticeship'), ('Training', 'Training'), ('Product Management', 'Product Management'), ('Language', 'Language'), ('Social Good', 'Social Good'), ('Open Ended', 'Open Ended'), ('Machine Learning/AI', 'Machine Learning/AI'), ('Blockchain', 'Blockchain'), ('Design', 'Design'), ('Web', 'Web'), ('AR/VR', 'AR/VR'), ('Gaming', 'Gaming'), ('Fintech', 'Fintech'), ('IoT', 'IoT'), ('DevOps', 'DevOps'), ('Cloud', 'Cloud'), ('Lifehacks', 'Lifehacks'), ('Cybersecurity', 'Cybersecurity'), ('Voice skills', 'Voice skills'), ('Mobile', 'Mobile'), ('Music/Art', 'Music/Art')], max_length=258),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Externship', 'Externship'), ('Student Program', 'Student Program'), ('Scholarship', 'Scholarship'), ('Apprenticeship', 'Apprenticeship'), ('Training', 'Training'), ('Product Management', 'Product Management'), ('Language', 'Language'), ('Social Good', 'Social Good'), ('Open Ended', 'Open Ended'), ('Machine Learning/AI', 'Machine Learning/AI'), ('Blockchain', 'Blockchain'), ('Design', 'Design'), ('Web', 'Web'), ('AR/VR', 'AR/VR'), ('Gaming', 'Gaming'), ('Fintech', 'Fintech'), ('IoT', 'IoT'), ('DevOps', 'DevOps'), ('Cloud', 'Cloud'), ('Lifehacks', 'Lifehacks'), ('Cybersecurity', 'Cybersecurity'), ('Voice skills', 'Voice skills'), ('Mobile', 'Mobile'), ('Music/Art', 'Music/Art')], max_length=258),
        ),
    ]
