# Generated by Django 4.0.6 on 2022-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allops', '0006_alter_mails_fields_alter_opportunity_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
